version: "2"  

run: 
  timeout: 5m  # Максимальное время выполнения анализа
  relative-path-mode: gomod  # Пути к файлам интерпретируются относительно корня go-модуля
  issues-exit-code: 1  # Код выхода = 1, если найдены ошибки (полезно для CI)
  tests: true  # Анализировать также _test.go файлы
  modules-download-mode: readonly  # Не разрешать загрузку зависимостей во время анализа (безопасно и быстрее на CI)

output: # Настройки вывода результатов линтинга
  formats:
    text: # Формат вывода в терминал
      print-linter-name: true  # Показывать имя линтера рядом с каждым сообщением
      print-issued-lines: true  # Показывать строку кода, где найдена проблема
      colors: true  # Использовать цветной вывод (для лучшей читаемости)

issues: # Общие настройки для обработки проблем
  max-issues-per-linter: 0  # Без лимита на количество ошибок от одного линтера
  max-same-issues: 0  # Без лимита на количество одинаковых ошибок
  uniq-by-line: true  # Отображать максимум одну ошибку на строку (избегает спама от разных линтеров по одной строке)

linters: # Список активных и отключённых линтеров
  default: standard  # Набор линтеров по умолчанию