# https://taskfile.dev

version: '3'

vars:
  GO_VERSION: '1.25'
  GOFUMPT_VERSION: 'v0.8.0'
  GCI_VERSION: 'v0.13.6'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GO_OAPI_MERGE_VERSION: 'v1.1.2'
  OAPI_CODEGEN_VERSION: 'v2.4.0'
  BUF_VERSION: '1.53.0'
  PROTOC_GEN_GO_VERSION: 'v1.36.6'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.5.1'

  GREETING: Hello, World!
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GO_OAPI_MERGE: '{{.BIN_DIR}}/go-oapi-merge'
  BUF: '{{.BIN_DIR}}/buf'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'


  OPENAPI_MAIN_FILE_PATH: '{{.ROOT_DIR}}/services/store/api/petstore/v1/petstore.openapi.yaml'
  OPENAPI_RESULT_FILE_PATH:  '{{.ROOT_DIR}}/services/store/api/bundles/petstore.openapi.v1.bundle.yaml'
  OPENAPI_PING_FILE_PATH:  '{{.ROOT_DIR}}/services/store/api/bundles/ping.yaml'
  ## Order
  OPENAPI_ORDER_FILE_PATH: '{{.ROOT_DIR}}/shared/api/order/v1/order.openapi.yaml'
  OPENAPI_ORDER_RESULT_FILE_PATH:  '{{.ROOT_DIR}}/shared/api/bundles/order.openapi.v1.bundle.yaml'
  ORDER_CODEGEN_FILE_PATH: '{{.ROOT_DIR}}/services/order/.oapi-codegen-order.yaml'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    cmds:
      - go build ./main.go

  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}
  
  format:
    desc: "Форматирует весь проект gofumpt + gci"
    deps: [ install-formatters ]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."
        find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
      - |
        echo "🎯 Сортируем импорты через gci ..."
        find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/neogna74/)" {} +

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [ install-golangci-lint ]
    cmds:
      - '{{.GOLANGCI_LINT}} run ./... --config=.golangci.yml'

  install-go-oapi-merge:
    desc: "Устанавливаем утилиту для мержа OAPI файлов в один (замена redocli)"
    cmds:
      - |
        echo "📦 Устанавливаем go-oapi-merge {{.GO_OAPI_MERGE_VERSION}}..."
        GOBIN={{.BIN_DIR}} go install github.com/NoL1m1ts/go-oapi-merge@{{.GO_OAPI_MERGE_VERSION}}
  go-oapi-merge:petstore-file-merge:
    desc: "Собираем единый файл спеки"
    deps: [install-go-oapi-merge]
    cmds:
     - '{{.GO_OAPI_MERGE}} --input {{.OPENAPI_MAIN_FILE_PATH}} --output {{.OPENAPI_RESULT_FILE_PATH}}' 
  
  oapi-codegen-install:
    desc: "Устанавливает oapi-codegen в каталог bin"
    cmds:
      - |
        [ -f {{.BIN_DIR}}/oapi-codegen ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Устанавливаем oapi-codegen ..."
          GOBIN={{.BIN_DIR}} go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@{{.OAPI_CODEGEN_VERSION}}
        }
    status:
      - test -x {{.BIN_DIR}}/oapi-codegen

  oapi-generate:
    desc: "Генерирует код по OpenAPI спецификации"
    cmds:
      - |
        echo "🛠  Генерируем код по OpenAPI спецификации..."
        {{.BIN_DIR}}/oapi-codegen -config .oapi-codegen.yaml {{.OPENAPI_RESULT_FILE_PATH}}

  oapi-generate-ping:
    desc: "Генерирует код по OpenAPI спецификации"
    cmds:
      - |
        echo "🛠  Генерируем код по OpenAPI спецификации..."
        {{.BIN_DIR}}/oapi-codegen -config .oapi-codegen-ping.yaml {{.OPENAPI_PING_FILE_PATH}}

  go-oapi-merge:order-svc-file-merge:
    desc: "Собираем единый файл спеки order-svc"
    deps: [install-go-oapi-merge]
    cmds:
      - '{{.GO_OAPI_MERGE}} --input {{.OPENAPI_ORDER_FILE_PATH}} --output {{.OPENAPI_ORDER_RESULT_FILE_PATH}}'

  oapi-generate-order:
    desc: "Генерирует код по OpenAPI спецификации order-svc"
    cmds:
      - |
        echo "🛠  Генерируем код по OpenAPI спецификации..."
        {{.BIN_DIR}}/oapi-codegen -config {{.ORDER_CODEGEN_FILE_PATH}} {{.OPENAPI_ORDER_RESULT_FILE_PATH}}

  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.BUF}} ] || {
          echo '📦 Устанавливаем buf {{.BUF_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@v{{.BUF_VERSION}}
        }
    status:
      - test -x {{.BUF}}

  proto:install-plugins:
    desc: "Устанавливает protoc плагины в каталог bin"
    cmds:
      - |
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo '📦 Installing protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo '📦 Installing protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
        }

  proto:lint:
    deps: [ install-buf, proto:install-plugins ]
    desc: Проверка .proto-файлов на соответствие стилю
    dir: proto
    cmds:
      - '{{.BUF}} lint'

  proto:gen:
    deps: [ install-buf, proto:install-plugins, proto:lint ]
    desc: Генерация Go-кода из .proto
    dir: proto
    cmds:
      - '{{.BUF}} generate'
