// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: starship/inventory/v1/inventory.proto

package inventory_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Category enum
type Category int32

const (
	Category_CATEGORY_UNKNOWN_UNSPECIFIED Category = 0
	Category_CATEGORY_ENGINE              Category = 1
	Category_CATEGORY_FUEL                Category = 2
	Category_CATEGORY_PORTHOLE            Category = 3
	Category_CATEGORY_WING                Category = 4
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNKNOWN_UNSPECIFIED",
		1: "CATEGORY_ENGINE",
		2: "CATEGORY_FUEL",
		3: "CATEGORY_PORTHOLE",
		4: "CATEGORY_WING",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNKNOWN_UNSPECIFIED": 0,
		"CATEGORY_ENGINE":              1,
		"CATEGORY_FUEL":                2,
		"CATEGORY_PORTHOLE":            3,
		"CATEGORY_WING":                4,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_starship_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_starship_inventory_v1_inventory_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// Part spare part struct
type Part struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity int64                  `protobuf:"varint,5,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Category      []Category             `protobuf:"varint,6,rep,packed,name=category,proto3,enum=starship.inventory.v1.Category" json:"category,omitempty"`
	Dimentions    *Dimentions            `protobuf:"bytes,7,opt,name=dimentions,proto3" json:"dimentions,omitempty"`
	Manufacturer  *Manufacturer          `protobuf:"bytes,8,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]*Value      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Part) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Part) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Part) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Part) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Part) GetCategory() []Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Part) GetDimentions() *Dimentions {
	if x != nil {
		return x.Dimentions
	}
	return nil
}

func (x *Part) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *Part) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Part) GetMetadata() map[string]*Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Part) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Part) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Dimentions
type Dimentions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        float64                `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
	Width         float64                `protobuf:"fixed64,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"`
	Weiht         float64                `protobuf:"fixed64,4,opt,name=weiht,proto3" json:"weiht,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimentions) Reset() {
	*x = Dimentions{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimentions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimentions) ProtoMessage() {}

func (x *Dimentions) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimentions.ProtoReflect.Descriptor instead.
func (*Dimentions) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Dimentions) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Dimentions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Dimentions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Dimentions) GetWeiht() float64 {
	if x != nil {
		return x.Weiht
	}
	return 0
}

// Manufacturer
type Manufacturer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Website       string                 `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Manufacturer) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

// PartsFilter
type PartsFilter struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Uuids                 []string               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Names                 []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Categories            []Category             `protobuf:"varint,3,rep,packed,name=categories,proto3,enum=starship.inventory.v1.Category" json:"categories,omitempty"`
	ManufacturerCountries []string               `protobuf:"bytes,4,rep,name=manufacturer_countries,json=manufacturerCountries,proto3" json:"manufacturer_countries,omitempty"`
	Tags                  []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PartsFilter) Reset() {
	*x = PartsFilter{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartsFilter) ProtoMessage() {}

func (x *PartsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartsFilter.ProtoReflect.Descriptor instead.
func (*PartsFilter) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *PartsFilter) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *PartsFilter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PartsFilter) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PartsFilter) GetManufacturerCountries() []string {
	if x != nil {
		return x.ManufacturerCountries
	}
	return nil
}

func (x *PartsFilter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Reqests/Response messages
// GetInventoryPartRequest
type GetPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartRequest) Reset() {
	*x = GetPartRequest{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartRequest) ProtoMessage() {}

func (x *GetPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartRequest.ProtoReflect.Descriptor instead.
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetPartRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// InventoryPartResponse retunrs uuid of spare part
type InventoryPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryPartResponse) Reset() {
	*x = InventoryPartResponse{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryPartResponse) ProtoMessage() {}

func (x *InventoryPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryPartResponse.ProtoReflect.Descriptor instead.
func (*InventoryPartResponse) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryPartResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// ListInventoryPartsRequest  request
type ListPartsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *PartsFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsRequest) Reset() {
	*x = ListPartsRequest{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsRequest) ProtoMessage() {}

func (x *ListPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsRequest.ProtoReflect.Descriptor instead.
func (*ListPartsRequest) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ListPartsRequest) GetFilter() *PartsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// ListInventoryPartsResponse
type ListInventoryPartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*Part                `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInventoryPartsResponse) Reset() {
	*x = ListInventoryPartsResponse{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventoryPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventoryPartsResponse) ProtoMessage() {}

func (x *ListInventoryPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventoryPartsResponse.ProtoReflect.Descriptor instead.
func (*ListInventoryPartsResponse) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ListInventoryPartsResponse) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

// Value for metadata value
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MetadataOneof:
	//
	//	*Value_StringValue
	//	*Value_Int64Value
	//	*Value_DoubleValue
	//	*Value_BoolValue
	MetadataOneof isValue_MetadataOneof `protobuf_oneof:"metadata_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_starship_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_starship_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *Value) GetMetadataOneof() isValue_MetadataOneof {
	if x != nil {
		return x.MetadataOneof
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.MetadataOneof.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.MetadataOneof.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.MetadataOneof.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.MetadataOneof.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isValue_MetadataOneof interface {
	isValue_MetadataOneof()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_MetadataOneof() {}

func (*Value_Int64Value) isValue_MetadataOneof() {}

func (*Value_DoubleValue) isValue_MetadataOneof() {}

func (*Value_BoolValue) isValue_MetadataOneof() {}

var File_starship_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_starship_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"%starship/inventory/v1/inventory.proto\x12\x15starship.inventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x05\n" +
	"\x04Part\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x05 \x01(\x03R\rstockQuantity\x12;\n" +
	"\bcategory\x18\x06 \x03(\x0e2\x1f.starship.inventory.v1.CategoryR\bcategory\x12A\n" +
	"\n" +
	"dimentions\x18\a \x01(\v2!.starship.inventory.v1.DimentionsR\n" +
	"dimentions\x12G\n" +
	"\fmanufacturer\x18\b \x01(\v2#.starship.inventory.v1.ManufacturerR\fmanufacturer\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12E\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2).starship.inventory.v1.Part.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aY\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.starship.inventory.v1.ValueR\x05value:\x028\x01\"h\n" +
	"\n" +
	"Dimentions\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x01R\x06height\x12\x14\n" +
	"\x05weiht\x18\x04 \x01(\x01R\x05weiht\"V\n" +
	"\fManufacturer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\"\xc5\x01\n" +
	"\vPartsFilter\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12?\n" +
	"\n" +
	"categories\x18\x03 \x03(\x0e2\x1f.starship.inventory.v1.CategoryR\n" +
	"categories\x125\n" +
	"\x16manufacturer_countries\x18\x04 \x03(\tR\x15manufacturerCountries\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"$\n" +
	"\x0eGetPartRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"+\n" +
	"\x15InventoryPartResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"N\n" +
	"\x10ListPartsRequest\x12:\n" +
	"\x06filter\x18\x01 \x01(\v2\".starship.inventory.v1.PartsFilterR\x06filter\"O\n" +
	"\x1aListInventoryPartsResponse\x121\n" +
	"\x05parts\x18\x01 \x03(\v2\x1b.starship.inventory.v1.PartR\x05parts\"\xa7\x01\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\x10\n" +
	"\x0emetadata_oneof*~\n" +
	"\bCategory\x12 \n" +
	"\x1cCATEGORY_UNKNOWN_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCATEGORY_ENGINE\x10\x01\x12\x11\n" +
	"\rCATEGORY_FUEL\x10\x02\x12\x15\n" +
	"\x11CATEGORY_PORTHOLE\x10\x03\x12\x11\n" +
	"\rCATEGORY_WING\x10\x042\xe3\x01\n" +
	"\x18StarshipInventoryService\x12^\n" +
	"\aGetPart\x12%.starship.inventory.v1.GetPartRequest\x1a,.starship.inventory.v1.InventoryPartResponse\x12g\n" +
	"\tListParts\x12'.starship.inventory.v1.ListPartsRequest\x1a1.starship.inventory.v1.ListInventoryPartsResponseBTZRgithub.com/neogan74/go-pet-store/sertvices/pkg/startship/inventory/v1;inventory_v1b\x06proto3"

var (
	file_starship_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_starship_inventory_v1_inventory_proto_rawDescData []byte
)

func file_starship_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_starship_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_starship_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_starship_inventory_v1_inventory_proto_rawDesc), len(file_starship_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_starship_inventory_v1_inventory_proto_rawDescData
}

var file_starship_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_starship_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_starship_inventory_v1_inventory_proto_goTypes = []any{
	(Category)(0),                      // 0: starship.inventory.v1.Category
	(*Part)(nil),                       // 1: starship.inventory.v1.Part
	(*Dimentions)(nil),                 // 2: starship.inventory.v1.Dimentions
	(*Manufacturer)(nil),               // 3: starship.inventory.v1.Manufacturer
	(*PartsFilter)(nil),                // 4: starship.inventory.v1.PartsFilter
	(*GetPartRequest)(nil),             // 5: starship.inventory.v1.GetPartRequest
	(*InventoryPartResponse)(nil),      // 6: starship.inventory.v1.InventoryPartResponse
	(*ListPartsRequest)(nil),           // 7: starship.inventory.v1.ListPartsRequest
	(*ListInventoryPartsResponse)(nil), // 8: starship.inventory.v1.ListInventoryPartsResponse
	(*Value)(nil),                      // 9: starship.inventory.v1.Value
	nil,                                // 10: starship.inventory.v1.Part.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_starship_inventory_v1_inventory_proto_depIdxs = []int32{
	0,  // 0: starship.inventory.v1.Part.category:type_name -> starship.inventory.v1.Category
	2,  // 1: starship.inventory.v1.Part.dimentions:type_name -> starship.inventory.v1.Dimentions
	3,  // 2: starship.inventory.v1.Part.manufacturer:type_name -> starship.inventory.v1.Manufacturer
	10, // 3: starship.inventory.v1.Part.metadata:type_name -> starship.inventory.v1.Part.MetadataEntry
	11, // 4: starship.inventory.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: starship.inventory.v1.Part.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: starship.inventory.v1.PartsFilter.categories:type_name -> starship.inventory.v1.Category
	4,  // 7: starship.inventory.v1.ListPartsRequest.filter:type_name -> starship.inventory.v1.PartsFilter
	1,  // 8: starship.inventory.v1.ListInventoryPartsResponse.parts:type_name -> starship.inventory.v1.Part
	9,  // 9: starship.inventory.v1.Part.MetadataEntry.value:type_name -> starship.inventory.v1.Value
	5,  // 10: starship.inventory.v1.StarshipInventoryService.GetPart:input_type -> starship.inventory.v1.GetPartRequest
	7,  // 11: starship.inventory.v1.StarshipInventoryService.ListParts:input_type -> starship.inventory.v1.ListPartsRequest
	6,  // 12: starship.inventory.v1.StarshipInventoryService.GetPart:output_type -> starship.inventory.v1.InventoryPartResponse
	8,  // 13: starship.inventory.v1.StarshipInventoryService.ListParts:output_type -> starship.inventory.v1.ListInventoryPartsResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_starship_inventory_v1_inventory_proto_init() }
func file_starship_inventory_v1_inventory_proto_init() {
	if File_starship_inventory_v1_inventory_proto != nil {
		return
	}
	file_starship_inventory_v1_inventory_proto_msgTypes[8].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_starship_inventory_v1_inventory_proto_rawDesc), len(file_starship_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_starship_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_starship_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_starship_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_starship_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_starship_inventory_v1_inventory_proto = out.File
	file_starship_inventory_v1_inventory_proto_goTypes = nil
	file_starship_inventory_v1_inventory_proto_depIdxs = nil
}
