// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: starship/maintenance/v1/starship.proto

package maintenance_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//	Enums
//
// Ship Status object - represent current status of a starship
type ShipStatus int32

const (
	ShipStatus_SHIP_STATUS_UNSPECIFIED ShipStatus = 0
	ShipStatus_SHIP_STATUS_ACTIVE      ShipStatus = 1
	ShipStatus_SHIP_STATUS_MAINTENANCE ShipStatus = 2
	ShipStatus_SHIP_STATUS_INACTIVE    ShipStatus = 3
)

// Enum value maps for ShipStatus.
var (
	ShipStatus_name = map[int32]string{
		0: "SHIP_STATUS_UNSPECIFIED",
		1: "SHIP_STATUS_ACTIVE",
		2: "SHIP_STATUS_MAINTENANCE",
		3: "SHIP_STATUS_INACTIVE",
	}
	ShipStatus_value = map[string]int32{
		"SHIP_STATUS_UNSPECIFIED": 0,
		"SHIP_STATUS_ACTIVE":      1,
		"SHIP_STATUS_MAINTENANCE": 2,
		"SHIP_STATUS_INACTIVE":    3,
	}
)

func (x ShipStatus) Enum() *ShipStatus {
	p := new(ShipStatus)
	*p = x
	return p
}

func (x ShipStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_starship_maintenance_v1_starship_proto_enumTypes[0].Descriptor()
}

func (ShipStatus) Type() protoreflect.EnumType {
	return &file_starship_maintenance_v1_starship_proto_enumTypes[0]
}

func (x ShipStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipStatus.Descriptor instead.
func (ShipStatus) EnumDescriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{0}
}

// Task Status object - represent current status of a maintenance task
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_TODO        TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_TODO",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_COMPLETED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_TODO":        1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_COMPLETED":   3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_starship_maintenance_v1_starship_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_starship_maintenance_v1_starship_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{1}
}

// Priority object - represent priority level of a maintenance task
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_MEDIUM      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_CRITICAL    Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_MEDIUM":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_CRITICAL":    4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_starship_maintenance_v1_starship_proto_enumTypes[2].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_starship_maintenance_v1_starship_proto_enumTypes[2]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{2}
}

// Core Data Models
// Snip - is object represent start ship
type Ship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipId        string                 `protobuf:"bytes,1,opt,name=ship_id,json=shipId,proto3" json:"ship_id,omitempty"`
	ShipName      string                 `protobuf:"bytes,2,opt,name=ship_name,json=shipName,proto3" json:"ship_name,omitempty"`
	Status        ShipStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=starship.maintenance.v1.ShipStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ship) Reset() {
	*x = Ship{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ship) ProtoMessage() {}

func (x *Ship) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ship.ProtoReflect.Descriptor instead.
func (*Ship) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{0}
}

func (x *Ship) GetShipId() string {
	if x != nil {
		return x.ShipId
	}
	return ""
}

func (x *Ship) GetShipName() string {
	if x != nil {
		return x.ShipName
	}
	return ""
}

func (x *Ship) GetStatus() ShipStatus {
	if x != nil {
		return x.Status
	}
	return ShipStatus_SHIP_STATUS_UNSPECIFIED
}

func (x *Ship) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Maintenance Task object - represent a maintenance task for a starship
type MaintenanceTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ShipId        string                 `protobuf:"bytes,2,opt,name=ship_id,json=shipId,proto3" json:"ship_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=starship.maintenance.v1.TaskStatus" json:"status,omitempty"`
	Priority      Priority               `protobuf:"varint,6,opt,name=priority,proto3,enum=starship.maintenance.v1.Priority" json:"priority,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,7,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceTask) Reset() {
	*x = MaintenanceTask{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceTask) ProtoMessage() {}

func (x *MaintenanceTask) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceTask.ProtoReflect.Descriptor instead.
func (*MaintenanceTask) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{1}
}

func (x *MaintenanceTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MaintenanceTask) GetShipId() string {
	if x != nil {
		return x.ShipId
	}
	return ""
}

func (x *MaintenanceTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaintenanceTask) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MaintenanceTask) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *MaintenanceTask) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *MaintenanceTask) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *MaintenanceTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MaintenanceTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MaintenanceTask) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

// Request/Response Messages
// Requests and responses for service methods
type CreateMaintenanceTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipId        string                 `protobuf:"bytes,1,opt,name=ship_id,json=shipId,proto3" json:"ship_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=starship.maintenance.v1.Priority" json:"priority,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,5,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMaintenanceTaskRequest) Reset() {
	*x = CreateMaintenanceTaskRequest{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMaintenanceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMaintenanceTaskRequest) ProtoMessage() {}

func (x *CreateMaintenanceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMaintenanceTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateMaintenanceTaskRequest) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMaintenanceTaskRequest) GetShipId() string {
	if x != nil {
		return x.ShipId
	}
	return ""
}

func (x *CreateMaintenanceTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMaintenanceTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMaintenanceTaskRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateMaintenanceTaskRequest) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *CreateMaintenanceTaskRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

// GetMaintenanceTaskRequest - request to get a specific maintenance task by ID
type GetMaintenanceTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaintenanceTaskRequest) Reset() {
	*x = GetMaintenanceTaskRequest{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaintenanceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaintenanceTaskRequest) ProtoMessage() {}

func (x *GetMaintenanceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaintenanceTaskRequest.ProtoReflect.Descriptor instead.
func (*GetMaintenanceTaskRequest) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{3}
}

func (x *GetMaintenanceTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// UpdateMaintenanceTaskRequest - request to update an existing maintenance task
type UpdateMaintenanceTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=starship.maintenance.v1.TaskStatus" json:"status,omitempty"`
	Priority      Priority               `protobuf:"varint,5,opt,name=priority,proto3,enum=starship.maintenance.v1.Priority" json:"priority,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,6,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMaintenanceTaskRequest) Reset() {
	*x = UpdateMaintenanceTaskRequest{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMaintenanceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMaintenanceTaskRequest) ProtoMessage() {}

func (x *UpdateMaintenanceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMaintenanceTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateMaintenanceTaskRequest) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMaintenanceTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateMaintenanceTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMaintenanceTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMaintenanceTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *UpdateMaintenanceTaskRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *UpdateMaintenanceTaskRequest) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *UpdateMaintenanceTaskRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

// ListMaintenanceTasksRequest - request to list maintenance tasks with optional filters
type ListMaintenanceTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipId        string                 `protobuf:"bytes,1,opt,name=ship_id,json=shipId,proto3" json:"ship_id,omitempty"`                            // Optional filter by ship
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=starship.maintenance.v1.TaskStatus" json:"status,omitempty"` // Optional filter by status
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaintenanceTasksRequest) Reset() {
	*x = ListMaintenanceTasksRequest{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaintenanceTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaintenanceTasksRequest) ProtoMessage() {}

func (x *ListMaintenanceTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaintenanceTasksRequest.ProtoReflect.Descriptor instead.
func (*ListMaintenanceTasksRequest) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{5}
}

func (x *ListMaintenanceTasksRequest) GetShipId() string {
	if x != nil {
		return x.ShipId
	}
	return ""
}

func (x *ListMaintenanceTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListMaintenanceTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMaintenanceTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListMaintenanceTasksResponse - response containing a list of maintenance tasks
type ListMaintenanceTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*MaintenanceTask     `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaintenanceTasksResponse) Reset() {
	*x = ListMaintenanceTasksResponse{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaintenanceTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaintenanceTasksResponse) ProtoMessage() {}

func (x *ListMaintenanceTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaintenanceTasksResponse.ProtoReflect.Descriptor instead.
func (*ListMaintenanceTasksResponse) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{6}
}

func (x *ListMaintenanceTasksResponse) GetTasks() []*MaintenanceTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListMaintenanceTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListMaintenanceTasksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetShipRequest - request to get a specific ship by ID
type GetShipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipId        string                 `protobuf:"bytes,1,opt,name=ship_id,json=shipId,proto3" json:"ship_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipRequest) Reset() {
	*x = GetShipRequest{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipRequest) ProtoMessage() {}

func (x *GetShipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipRequest.ProtoReflect.Descriptor instead.
func (*GetShipRequest) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{7}
}

func (x *GetShipRequest) GetShipId() string {
	if x != nil {
		return x.ShipId
	}
	return ""
}

// ListShipsRequest - request to list ships with pagination
type ListShipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShipsRequest) Reset() {
	*x = ListShipsRequest{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShipsRequest) ProtoMessage() {}

func (x *ListShipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShipsRequest.ProtoReflect.Descriptor instead.
func (*ListShipsRequest) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{8}
}

func (x *ListShipsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListShipsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListShipsResponse - response containing a list of ships
type ListShipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ships         []*Ship                `protobuf:"bytes,1,rep,name=ships,proto3" json:"ships,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShipsResponse) Reset() {
	*x = ListShipsResponse{}
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShipsResponse) ProtoMessage() {}

func (x *ListShipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starship_maintenance_v1_starship_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShipsResponse.ProtoReflect.Descriptor instead.
func (*ListShipsResponse) Descriptor() ([]byte, []int) {
	return file_starship_maintenance_v1_starship_proto_rawDescGZIP(), []int{9}
}

func (x *ListShipsResponse) GetShips() []*Ship {
	if x != nil {
		return x.Ships
	}
	return nil
}

func (x *ListShipsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListShipsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_starship_maintenance_v1_starship_proto protoreflect.FileDescriptor

const file_starship_maintenance_v1_starship_proto_rawDesc = "" +
	"\n" +
	"&starship/maintenance/v1/starship.proto\x12\x17starship.maintenance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\x04Ship\x12\x17\n" +
	"\aship_id\x18\x01 \x01(\tR\x06shipId\x12\x1b\n" +
	"\tship_name\x18\x02 \x01(\tR\bshipName\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.starship.maintenance.v1.ShipStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc5\x03\n" +
	"\x0fMaintenanceTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aship_id\x18\x02 \x01(\tR\x06shipId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.starship.maintenance.v1.TaskStatusR\x06status\x12=\n" +
	"\bpriority\x18\x06 \x01(\x0e2!.starship.maintenance.v1.PriorityR\bpriority\x12\x1f\n" +
	"\vassigned_to\x18\a \x01(\tR\n" +
	"assignedTo\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x125\n" +
	"\bdue_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"\x86\x02\n" +
	"\x1cCreateMaintenanceTaskRequest\x12\x17\n" +
	"\aship_id\x18\x01 \x01(\tR\x06shipId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12=\n" +
	"\bpriority\x18\x04 \x01(\x0e2!.starship.maintenance.v1.PriorityR\bpriority\x12\x1f\n" +
	"\vassigned_to\x18\x05 \x01(\tR\n" +
	"assignedTo\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"4\n" +
	"\x19GetMaintenanceTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xc3\x02\n" +
	"\x1cUpdateMaintenanceTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.starship.maintenance.v1.TaskStatusR\x06status\x12=\n" +
	"\bpriority\x18\x05 \x01(\x0e2!.starship.maintenance.v1.PriorityR\bpriority\x12\x1f\n" +
	"\vassigned_to\x18\x06 \x01(\tR\n" +
	"assignedTo\x125\n" +
	"\bdue_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"\xaf\x01\n" +
	"\x1bListMaintenanceTasksRequest\x12\x17\n" +
	"\aship_id\x18\x01 \x01(\tR\x06shipId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.starship.maintenance.v1.TaskStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xa7\x01\n" +
	"\x1cListMaintenanceTasksResponse\x12>\n" +
	"\x05tasks\x18\x01 \x03(\v2(.starship.maintenance.v1.MaintenanceTaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\")\n" +
	"\x0eGetShipRequest\x12\x17\n" +
	"\aship_id\x18\x01 \x01(\tR\x06shipId\"N\n" +
	"\x10ListShipsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x91\x01\n" +
	"\x11ListShipsResponse\x123\n" +
	"\x05ships\x18\x01 \x03(\v2\x1d.starship.maintenance.v1.ShipR\x05ships\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount*x\n" +
	"\n" +
	"ShipStatus\x12\x1b\n" +
	"\x17SHIP_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SHIP_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17SHIP_STATUS_MAINTENANCE\x10\x02\x12\x18\n" +
	"\x14SHIP_STATUS_INACTIVE\x10\x03*w\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TASK_STATUS_TODO\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03*u\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x042\xc1\x05\n" +
	"\x1aStarshipMaintenanceService\x12x\n" +
	"\x15CreateMaintenanceTask\x125.starship.maintenance.v1.CreateMaintenanceTaskRequest\x1a(.starship.maintenance.v1.MaintenanceTask\x12r\n" +
	"\x12GetMaintenanceTask\x122.starship.maintenance.v1.GetMaintenanceTaskRequest\x1a(.starship.maintenance.v1.MaintenanceTask\x12x\n" +
	"\x15UpdateMaintenanceTask\x125.starship.maintenance.v1.UpdateMaintenanceTaskRequest\x1a(.starship.maintenance.v1.MaintenanceTask\x12\x83\x01\n" +
	"\x14ListMaintenanceTasks\x124.starship.maintenance.v1.ListMaintenanceTasksRequest\x1a5.starship.maintenance.v1.ListMaintenanceTasksResponse\x12Q\n" +
	"\aGetShip\x12'.starship.maintenance.v1.GetShipRequest\x1a\x1d.starship.maintenance.v1.Ship\x12b\n" +
	"\tListShips\x12).starship.maintenance.v1.ListShipsRequest\x1a*.starship.maintenance.v1.ListShipsResponseB\\ZZgithub.com/neogan74/go-pet-store/services/pkg/proto/starship/maintenance/v1;maintenance_v1b\x06proto3"

var (
	file_starship_maintenance_v1_starship_proto_rawDescOnce sync.Once
	file_starship_maintenance_v1_starship_proto_rawDescData []byte
)

func file_starship_maintenance_v1_starship_proto_rawDescGZIP() []byte {
	file_starship_maintenance_v1_starship_proto_rawDescOnce.Do(func() {
		file_starship_maintenance_v1_starship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_starship_maintenance_v1_starship_proto_rawDesc), len(file_starship_maintenance_v1_starship_proto_rawDesc)))
	})
	return file_starship_maintenance_v1_starship_proto_rawDescData
}

var file_starship_maintenance_v1_starship_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_starship_maintenance_v1_starship_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_starship_maintenance_v1_starship_proto_goTypes = []any{
	(ShipStatus)(0),                      // 0: starship.maintenance.v1.ShipStatus
	(TaskStatus)(0),                      // 1: starship.maintenance.v1.TaskStatus
	(Priority)(0),                        // 2: starship.maintenance.v1.Priority
	(*Ship)(nil),                         // 3: starship.maintenance.v1.Ship
	(*MaintenanceTask)(nil),              // 4: starship.maintenance.v1.MaintenanceTask
	(*CreateMaintenanceTaskRequest)(nil), // 5: starship.maintenance.v1.CreateMaintenanceTaskRequest
	(*GetMaintenanceTaskRequest)(nil),    // 6: starship.maintenance.v1.GetMaintenanceTaskRequest
	(*UpdateMaintenanceTaskRequest)(nil), // 7: starship.maintenance.v1.UpdateMaintenanceTaskRequest
	(*ListMaintenanceTasksRequest)(nil),  // 8: starship.maintenance.v1.ListMaintenanceTasksRequest
	(*ListMaintenanceTasksResponse)(nil), // 9: starship.maintenance.v1.ListMaintenanceTasksResponse
	(*GetShipRequest)(nil),               // 10: starship.maintenance.v1.GetShipRequest
	(*ListShipsRequest)(nil),             // 11: starship.maintenance.v1.ListShipsRequest
	(*ListShipsResponse)(nil),            // 12: starship.maintenance.v1.ListShipsResponse
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_starship_maintenance_v1_starship_proto_depIdxs = []int32{
	0,  // 0: starship.maintenance.v1.Ship.status:type_name -> starship.maintenance.v1.ShipStatus
	13, // 1: starship.maintenance.v1.Ship.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: starship.maintenance.v1.MaintenanceTask.status:type_name -> starship.maintenance.v1.TaskStatus
	2,  // 3: starship.maintenance.v1.MaintenanceTask.priority:type_name -> starship.maintenance.v1.Priority
	13, // 4: starship.maintenance.v1.MaintenanceTask.created_at:type_name -> google.protobuf.Timestamp
	13, // 5: starship.maintenance.v1.MaintenanceTask.updated_at:type_name -> google.protobuf.Timestamp
	13, // 6: starship.maintenance.v1.MaintenanceTask.due_date:type_name -> google.protobuf.Timestamp
	2,  // 7: starship.maintenance.v1.CreateMaintenanceTaskRequest.priority:type_name -> starship.maintenance.v1.Priority
	13, // 8: starship.maintenance.v1.CreateMaintenanceTaskRequest.due_date:type_name -> google.protobuf.Timestamp
	1,  // 9: starship.maintenance.v1.UpdateMaintenanceTaskRequest.status:type_name -> starship.maintenance.v1.TaskStatus
	2,  // 10: starship.maintenance.v1.UpdateMaintenanceTaskRequest.priority:type_name -> starship.maintenance.v1.Priority
	13, // 11: starship.maintenance.v1.UpdateMaintenanceTaskRequest.due_date:type_name -> google.protobuf.Timestamp
	1,  // 12: starship.maintenance.v1.ListMaintenanceTasksRequest.status:type_name -> starship.maintenance.v1.TaskStatus
	4,  // 13: starship.maintenance.v1.ListMaintenanceTasksResponse.tasks:type_name -> starship.maintenance.v1.MaintenanceTask
	3,  // 14: starship.maintenance.v1.ListShipsResponse.ships:type_name -> starship.maintenance.v1.Ship
	5,  // 15: starship.maintenance.v1.StarshipMaintenanceService.CreateMaintenanceTask:input_type -> starship.maintenance.v1.CreateMaintenanceTaskRequest
	6,  // 16: starship.maintenance.v1.StarshipMaintenanceService.GetMaintenanceTask:input_type -> starship.maintenance.v1.GetMaintenanceTaskRequest
	7,  // 17: starship.maintenance.v1.StarshipMaintenanceService.UpdateMaintenanceTask:input_type -> starship.maintenance.v1.UpdateMaintenanceTaskRequest
	8,  // 18: starship.maintenance.v1.StarshipMaintenanceService.ListMaintenanceTasks:input_type -> starship.maintenance.v1.ListMaintenanceTasksRequest
	10, // 19: starship.maintenance.v1.StarshipMaintenanceService.GetShip:input_type -> starship.maintenance.v1.GetShipRequest
	11, // 20: starship.maintenance.v1.StarshipMaintenanceService.ListShips:input_type -> starship.maintenance.v1.ListShipsRequest
	4,  // 21: starship.maintenance.v1.StarshipMaintenanceService.CreateMaintenanceTask:output_type -> starship.maintenance.v1.MaintenanceTask
	4,  // 22: starship.maintenance.v1.StarshipMaintenanceService.GetMaintenanceTask:output_type -> starship.maintenance.v1.MaintenanceTask
	4,  // 23: starship.maintenance.v1.StarshipMaintenanceService.UpdateMaintenanceTask:output_type -> starship.maintenance.v1.MaintenanceTask
	9,  // 24: starship.maintenance.v1.StarshipMaintenanceService.ListMaintenanceTasks:output_type -> starship.maintenance.v1.ListMaintenanceTasksResponse
	3,  // 25: starship.maintenance.v1.StarshipMaintenanceService.GetShip:output_type -> starship.maintenance.v1.Ship
	12, // 26: starship.maintenance.v1.StarshipMaintenanceService.ListShips:output_type -> starship.maintenance.v1.ListShipsResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_starship_maintenance_v1_starship_proto_init() }
func file_starship_maintenance_v1_starship_proto_init() {
	if File_starship_maintenance_v1_starship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_starship_maintenance_v1_starship_proto_rawDesc), len(file_starship_maintenance_v1_starship_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_starship_maintenance_v1_starship_proto_goTypes,
		DependencyIndexes: file_starship_maintenance_v1_starship_proto_depIdxs,
		EnumInfos:         file_starship_maintenance_v1_starship_proto_enumTypes,
		MessageInfos:      file_starship_maintenance_v1_starship_proto_msgTypes,
	}.Build()
	File_starship_maintenance_v1_starship_proto = out.File
	file_starship_maintenance_v1_starship_proto_goTypes = nil
	file_starship_maintenance_v1_starship_proto_depIdxs = nil
}
